<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Unpwn.Automation/Unpwn.Automation.csproj" />
    <ProjectReference Include="../../src/Unpwn.Providers/Unpwn.Providers.csproj" />
  </ItemGroup>
</Project>
