<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Unpwn.Application/Unpwn.Application.csproj" />
    <ProjectReference Include="../Unpwn.Core/Unpwn.Core.csproj" />
  </ItemGroup>
</Project>
