namespace Unpwn.Core;

internal static class RepositoryAccountClassificationAdditionalProviderData
{
    public static IReadOnlyList<AccountClassificationProviderRecord> CreateRecords(string provenanceId) =>
    [
        .. CreateEmailRecords(provenanceId),
        .. CreateFinancialRecords(provenanceId),
        .. CreateSecurityAndIdentityRecords(provenanceId),
        .. CreateCloudAndWorkRecords(provenanceId),
        .. CreateCommerceAndTravelRecords(provenanceId),
        .. CreateCommunicationRecords(provenanceId),
        .. CreateGamingRecords(provenanceId),
        .. CreateGovernmentHealthAndInsuranceRecords(provenanceId),
        .. CreateLowerImpactRecords(provenanceId),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateEmailRecords(string provenanceId) =>
    [
        Email("email-kolab-now", "Kolab Now", ["kolabnow.com"], provenanceId, "kolabnow"),
        Email("email-countermail", "CounterMail", ["countermail.com"], provenanceId, "countermail"),
        Email("email-migadu", "Migadu", ["migadu.com"], provenanceId, "migadu"),
        Email("email-purelymail", "Purelymail", ["purelymail.com"], provenanceId, "purelymail"),
        Email("email-mail-ee", "Mail.ee", ["mail.ee"], provenanceId, "mailee"),
        Email("email-abv", "ABV Mail", ["abv.bg"], provenanceId, "abvmail"),
        Email("email-mail-bg", "Mail.bg", ["mail.bg"], provenanceId, "mailbg"),
        Email("email-sapo", "SAPO Mail", ["sapo.pt"], provenanceId, "sapomail"),
        Email("email-daum", "Daum / Hanmail", ["daum.net", "hanmail.net"], provenanceId, "daummail", "hanmail"),
        Email("email-nate", "Nate Mail", ["nate.com"], provenanceId, "natemail"),
        Email("email-sina", "Sina Mail", ["sina.com", "sina.cn"], provenanceId, "sinamail"),
        Email("email-china-mobile", "China Mobile 139 Mail", ["139.com"], provenanceId, "139mail"),
        Email("email-centurylink", "CenturyLink Mail", ["centurylink.net", "q.com"], provenanceId,
            "centurylinkmail"),
        Email("email-verizon", "Verizon Mail", ["verizon.net"], provenanceId, "verizonmail"),
        Email("email-optimum", "Optimum Mail", ["optonline.net"], provenanceId, "optimummail"),
        Email("email-rogers", "Rogers Mail", ["rogers.com"], provenanceId, "rogersmail"),
        Email("email-telus", "TELUS Mail", ["telus.net"], provenanceId, "telusmail"),
        Email("email-shaw", "Shaw Mail", ["shaw.ca"], provenanceId, "shawmail"),
        Email("email-kpn", "KPN Mail", ["kpnmail.nl"], provenanceId, "kpnmail"),
        Email("email-ziggo", "Ziggo Mail", ["ziggo.nl"], provenanceId, "ziggomail"),
        Email("email-vodafone-de", "Vodafone / Arcor Mail", ["vodafone.de", "arcor.de"], provenanceId,
            "vodafonemail", "arcormail"),
        Email("email-oneandone", "1&1 Mail", ["1und1.de"], provenanceId, "1und1mail", "oneandone"),
        Email("email-telstra", "Telstra BigPond Mail", ["bigpond.com", "bigpond.net.au"], provenanceId,
            "bigpond", "telstramail"),
        Email("email-optus", "OptusNet Mail", ["optusnet.com.au"], provenanceId, "optusnet"),
        Email("email-centrum-cz", "Centrum.cz Mail", ["centrum.cz"], provenanceId, "centrummail"),
        Email("email-dir-bg", "Dir.bg Mail", ["dir.bg"], provenanceId, "dirbgmail"),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateFinancialRecords(string provenanceId) =>
    [
        Financial("critical-c24", "C24 Bank", ["c24.de"], provenanceId, "c24bank"),
        Financial("critical-tomorrow", "Tomorrow", ["tomorrow.one"], provenanceId, "tomorrowbanking"),
        Financial("critical-vivid", "Vivid Money", ["vivid.money"], provenanceId, "vividmoney"),
        Financial("critical-bunq", "bunq", ["bunq.com"], provenanceId, "bunq"),
        Financial("critical-qonto", "Qonto", ["qonto.com"], provenanceId, "qonto"),
        Financial("critical-neon", "neon", ["neon-free.ch"], provenanceId, "neonbank"),
        Financial("critical-yuh", "Yuh", ["yuh.com"], provenanceId, "yuh"),
        Financial("critical-zkb", "Zürcher Kantonalbank", ["zkb.ch"], provenanceId, "zkb"),
        Financial("critical-bcv", "Banque Cantonale Vaudoise", ["bcv.ch"], provenanceId, "bcv"),
        Financial("critical-migros-bank", "Migros Bank", ["migrosbank.ch"], provenanceId, "migrosbank"),
        Financial("critical-bank-cler", "Bank Cler", ["cler.ch"], provenanceId, "bankcler"),
        Financial("critical-bank-austria", "Bank Austria", ["bankaustria.at"], provenanceId, "bankaustria"),
        Financial("critical-easybank", "easybank", ["easybank.at"], provenanceId, "easybank"),
        Financial("critical-oberbank", "Oberbank", ["oberbank.at"], provenanceId, "oberbank"),
        Financial("critical-volksbank-wien", "Volksbank Wien", ["volksbankwien.at"], provenanceId,
            "volksbankwien"),
        Financial("critical-raiffeisen-at", "Raiffeisen Austria", ["raiffeisen.at"], provenanceId,
            "raiffeisenat"),
        Financial("critical-hsbc", "HSBC", ["hsbc.com"], provenanceId, "hsbc"),
        Financial("critical-nationwide", "Nationwide Building Society", ["nationwide.co.uk"], provenanceId,
            "nationwide"),
        Financial("critical-halifax", "Halifax", ["halifax.co.uk"], provenanceId, "halifax"),
        Financial("critical-tsb", "TSB", ["tsb.co.uk"], provenanceId, "tsb"),
        Financial("critical-metro-bank", "Metro Bank", ["metrobankonline.co.uk"], provenanceId, "metrobank"),
        Financial("critical-virgin-money", "Virgin Money", ["virginmoney.com"], provenanceId, "virginmoney"),
        Financial("critical-bbva", "BBVA", ["bbva.com"], provenanceId, "bbva"),
        Financial("critical-caixabank", "CaixaBank", ["caixabank.es"], provenanceId, "caixabank"),
        Financial("critical-banco-sabadell", "Banco Sabadell", ["bancsabadell.com"], provenanceId,
            "bancosabadell"),
        Financial("critical-bankinter", "Bankinter", ["bankinter.com"], provenanceId, "bankinter"),
        Financial("critical-openbank", "Openbank", ["openbank.es"], provenanceId, "openbank"),
        Financial("critical-unicredit-it", "UniCredit Italy", ["unicredit.it"], provenanceId, "unicreditit"),
        Financial("critical-intesa-sanpaolo", "Intesa Sanpaolo", ["intesasanpaolo.com"], provenanceId,
            "intesasanpaolo"),
        Financial("critical-fineco", "FinecoBank", ["finecobank.com"], provenanceId, "fineco"),
        Financial("critical-bper", "BPER Banca", ["bper.it"], provenanceId, "bper"),
        Financial("critical-banco-bpm", "Banco BPM", ["bancobpm.it"], provenanceId, "bancobpm"),
        Financial("critical-nordea", "Nordea", ["nordea.com"], provenanceId, "nordea"),
        Financial("critical-danske-bank", "Danske Bank", ["danskebank.com"], provenanceId, "danskebank"),
        Financial("critical-seb", "SEB", ["seb.se"], provenanceId, "sebbank"),
        Financial("critical-swedbank", "Swedbank", ["swedbank.com"], provenanceId, "swedbank"),
        Financial("critical-handelsbanken", "Handelsbanken", ["handelsbanken.com"], provenanceId,
            "handelsbanken"),
        Financial("critical-dnb", "DNB", ["dnb.no"], provenanceId, "dnb"),
        Financial("critical-lunar", "Lunar", ["lunar.app"], provenanceId, "lunarbank"),
        Financial("critical-pnc", "PNC Bank", ["pnc.com"], provenanceId, "pncbank"),
        Financial("critical-us-bank", "U.S. Bank", ["usbank.com"], provenanceId, "usbank"),
        Financial("critical-ally", "Ally Bank", ["ally.com"], provenanceId, "allybank"),
        Financial("critical-marcus", "Marcus by Goldman Sachs", ["marcus.com"], provenanceId, "marcus"),
        Financial("critical-morgan-stanley", "Morgan Stanley", ["morganstanley.com"], provenanceId,
            "morganstanley"),
        Financial("critical-etrade", "E*TRADE", ["etrade.com"], provenanceId, "etrade"),
        Financial("critical-sofi", "SoFi", ["sofi.com"], provenanceId, "sofi"),
        Financial("critical-chime", "Chime", ["chime.com"], provenanceId, "chime"),
        Financial("critical-dbs", "DBS Bank", ["dbs.com"], provenanceId, "dbsbank"),
        Financial("critical-ocbc", "OCBC Bank", ["ocbc.com"], provenanceId, "ocbcbank"),
        Financial("critical-uob", "UOB", ["uobgroup.com"], provenanceId, "uob"),
        Financial("critical-icbc", "ICBC", ["icbc.com.cn"], provenanceId, "icbc"),
        Financial("critical-bank-of-china", "Bank of China", ["bankofchina.com"], provenanceId, "bankofchina"),
        Financial("critical-mufg", "MUFG Bank", ["mufg.jp"], provenanceId, "mufgbank"),
        Financial("critical-smbc", "SMBC", ["smbc.co.jp"], provenanceId, "smbc"),
        Financial("critical-mizuho", "Mizuho Bank", ["mizuhobank.co.jp"], provenanceId, "mizuhobank"),
        Financial("critical-sbi", "State Bank of India", ["sbi.co.in"], provenanceId, "statebankofindia"),
        Financial("critical-hdfc", "HDFC Bank", ["hdfcbank.com"], provenanceId, "hdfcbank"),
        Financial("critical-icici", "ICICI Bank", ["icicibank.com"], provenanceId, "icicibank"),
        Financial("critical-skrill", "Skrill", ["skrill.com"], provenanceId, "skrill"),
        Financial("critical-neteller", "Neteller", ["neteller.com"], provenanceId, "neteller"),
        Financial("critical-paysafecard", "Paysafecard", ["paysafecard.com"], provenanceId, "paysafecard"),
        Financial("critical-mollie", "Mollie", ["mollie.com"], provenanceId, "mollie"),
        Financial("critical-checkout", "Checkout.com", ["checkout.com"], provenanceId, "checkoutcom"),
        Financial("critical-worldpay", "Worldpay", ["worldpay.com"], provenanceId, "worldpay"),
        Financial("critical-remitly", "Remitly", ["remitly.com"], provenanceId, "remitly"),
        Financial("critical-western-union", "Western Union", ["westernunion.com"], provenanceId,
            "westernunion"),
        Financial("critical-moneygram", "MoneyGram", ["moneygram.com"], provenanceId, "moneygram"),
        Financial("critical-crypto-com", "Crypto.com", ["crypto.com"], provenanceId, "cryptocom"),
        Financial("critical-gemini", "Gemini", ["gemini.com"], provenanceId, "gemini"),
        Financial("critical-bitstamp", "Bitstamp", ["bitstamp.net"], provenanceId, "bitstamp"),
        Financial("critical-bitfinex", "Bitfinex", ["bitfinex.com"], provenanceId, "bitfinex"),
        Financial("critical-bitget", "Bitget", ["bitget.com"], provenanceId, "bitget"),
        Financial("critical-bybit", "Bybit", ["bybit.com"], provenanceId, "bybit"),
        Financial("critical-kucoin", "KuCoin", ["kucoin.com"], provenanceId, "kucoin"),
        Financial("critical-okx", "OKX", ["okx.com"], provenanceId, "okx"),
        Financial("critical-cexio", "CEX.IO", ["cex.io"], provenanceId, "cexio"),
        Financial("critical-blockchain-com", "Blockchain.com", ["blockchain.com"], provenanceId,
            "blockchaincom"),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateSecurityAndIdentityRecords(
        string provenanceId) =>
    [
        Critical("critical-yubico", "Yubico", ["yubico.com"], provenanceId, SecurityBasis, "yubico"),
        Critical("critical-authy", "Authy", ["authy.com"], provenanceId, SecurityBasis, "authy"),
        Critical("critical-idme", "ID.me", ["id.me"], provenanceId, IdentityBasis, "idme"),
        Critical("critical-itsme", "itsme", ["itsme-id.com"], provenanceId, IdentityBasis, "itsme"),
        Critical("critical-expressvpn", "ExpressVPN", ["expressvpn.com"], provenanceId, SecurityBasis,
            "expressvpn"),
        Critical("critical-surfshark", "Surfshark", ["surfshark.com"], provenanceId, SecurityBasis, "surfshark"),
        Critical("critical-cyberghost", "CyberGhost", ["cyberghostvpn.com"], provenanceId, SecurityBasis,
            "cyberghost"),
        Critical("critical-pia", "Private Internet Access", ["privateinternetaccess.com"], provenanceId,
            SecurityBasis, "privateinternetaccess", "piavpn"),
        Critical("critical-mullvad", "Mullvad", ["mullvad.net"], provenanceId, SecurityBasis, "mullvad"),
        Critical("critical-firefox-account", "Mozilla account", ["accounts.firefox.com"], provenanceId,
            IdentityBasis, "mozillaaccount", "firefoxaccount"),
        Critical("critical-norton", "Norton", ["norton.com"], provenanceId, SecurityBasis, "norton"),
        Critical("critical-mcafee", "McAfee", ["mcafee.com"], provenanceId, SecurityBasis, "mcafee"),
        Critical("critical-malwarebytes", "Malwarebytes", ["malwarebytes.com"], provenanceId, SecurityBasis,
            "malwarebytes"),
        Critical("critical-eset", "ESET", ["eset.com"], provenanceId, SecurityBasis, "eset"),
        Critical("critical-kaspersky", "Kaspersky", ["kaspersky.com"], provenanceId, SecurityBasis, "kaspersky"),
        Critical("critical-avira", "Avira", ["avira.com"], provenanceId, SecurityBasis, "avira"),
        Critical("critical-sophos", "Sophos", ["sophos.com"], provenanceId, SecurityBasis, "sophos"),
        Critical("critical-trend-micro", "Trend Micro", ["trendmicro.com"], provenanceId, SecurityBasis,
            "trendmicro"),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateCloudAndWorkRecords(string provenanceId) =>
    [
        Critical("critical-openai", "OpenAI", ["openai.com"], provenanceId, CloudBasis, "openai", "chatgpt"),
        Critical("critical-anthropic", "Anthropic", ["anthropic.com", "claude.ai"], provenanceId, CloudBasis,
            "anthropic", "claude"),
        Critical("critical-huggingface", "Hugging Face", ["huggingface.co"], provenanceId, CloudBasis,
            "huggingface"),
        Critical("critical-replit", "Replit", ["replit.com"], provenanceId, CloudBasis, "replit"),
        Critical("critical-cursor", "Cursor", ["cursor.com"], provenanceId, CloudBasis, "cursor"),
        Critical("critical-stack-overflow", "Stack Overflow", ["stackoverflow.com"], provenanceId, CloudBasis,
            "stackoverflow"),
        Critical("critical-codeberg", "Codeberg", ["codeberg.org"], provenanceId, CloudBasis, "codeberg"),
        Critical("critical-sourceforge", "SourceForge", ["sourceforge.net"], provenanceId, CloudBasis,
            "sourceforge"),
        Critical("critical-sentry", "Sentry", ["sentry.io"], provenanceId, CloudBasis, "sentry"),
        Critical("critical-datadog", "Datadog", ["datadoghq.com"], provenanceId, CloudBasis, "datadog"),
        Critical("critical-new-relic", "New Relic", ["newrelic.com"], provenanceId, CloudBasis, "newrelic"),
        Critical("critical-grafana", "Grafana Cloud", ["grafana.com"], provenanceId, CloudBasis, "grafana"),
        Critical("critical-mongodb", "MongoDB", ["mongodb.com"], provenanceId, CloudBasis, "mongodb"),
        Critical("critical-redis", "Redis Cloud", ["redis.io"], provenanceId, CloudBasis, "redis"),
        Critical("critical-supabase", "Supabase", ["supabase.com"], provenanceId, CloudBasis, "supabase"),
        Critical("critical-render", "Render", ["render.com"], provenanceId, CloudBasis, "render"),
        Critical("critical-flyio", "Fly.io", ["fly.io"], provenanceId, CloudBasis, "flyio"),
        Critical("critical-linode", "Linode", ["linode.com"], provenanceId, CloudBasis, "linode"),
        Critical("critical-vultr", "Vultr", ["vultr.com"], provenanceId, CloudBasis, "vultr"),
        Critical("critical-hetzner", "Hetzner", ["hetzner.com"], provenanceId, CloudBasis, "hetzner"),
        Critical("critical-ovhcloud", "OVHcloud", ["ovhcloud.com"], provenanceId, CloudBasis, "ovhcloud"),
        Critical("critical-ionos", "IONOS", ["ionos.com", "ionos.de"], provenanceId, CloudBasis, "ionos"),
        Critical("critical-godaddy", "GoDaddy", ["godaddy.com"], provenanceId, CloudBasis, "godaddy"),
        Critical("critical-namecheap", "Namecheap", ["namecheap.com"], provenanceId, CloudBasis, "namecheap"),
        Critical("critical-gandi", "Gandi", ["gandi.net"], provenanceId, CloudBasis, "gandi"),
        Critical("critical-porkbun", "Porkbun", ["porkbun.com"], provenanceId, CloudBasis, "porkbun"),
        Critical("critical-squarespace", "Squarespace", ["squarespace.com"], provenanceId, CloudBasis,
            "squarespace"),
        Critical("critical-wix", "Wix", ["wix.com"], provenanceId, CloudBasis, "wix"),
        Critical("critical-wordpress-com", "WordPress.com", ["wordpress.com"], provenanceId, CloudBasis,
            "wordpresscom"),
        Critical("critical-pypi", "PyPI", ["pypi.org"], provenanceId, CloudBasis, "pypi"),
        Critical("critical-rubygems", "RubyGems", ["rubygems.org"], provenanceId, CloudBasis, "rubygems"),
        Critical("critical-packagist", "Packagist", ["packagist.org"], provenanceId, CloudBasis, "packagist"),
        Critical("critical-sonatype", "Sonatype / Maven Central", ["sonatype.com"],
            provenanceId, CloudBasis, "sonatype", "mavencentral"),
        Critical("critical-circleci", "CircleCI", ["circleci.com"], provenanceId, CloudBasis, "circleci"),
        Critical("critical-travis-ci", "Travis CI", ["travis-ci.com"], provenanceId, CloudBasis, "travisci"),
        Critical("critical-buildkite", "Buildkite", ["buildkite.com"], provenanceId, CloudBasis, "buildkite"),
        Critical("critical-notion", "Notion", ["notion.so"], provenanceId, WorkBasis, "notion"),
        Critical("critical-canva", "Canva", ["canva.com"], provenanceId, WorkBasis, "canva"),
        Critical("critical-figma", "Figma", ["figma.com"], provenanceId, WorkBasis, "figma"),
        Critical("critical-miro", "Miro", ["miro.com"], provenanceId, WorkBasis, "miro"),
        Critical("critical-linear", "Linear", ["linear.app"], provenanceId, WorkBasis, "linear"),
        Critical("critical-airtable", "Airtable", ["airtable.com"], provenanceId, WorkBasis, "airtable"),
        Critical("critical-asana", "Asana", ["asana.com"], provenanceId, WorkBasis, "asana"),
        Critical("critical-monday", "monday.com", ["monday.com"], provenanceId, WorkBasis, "mondaycom"),
        Critical("critical-clickup", "ClickUp", ["clickup.com"], provenanceId, WorkBasis, "clickup"),
        Critical("critical-gitbook", "GitBook", ["gitbook.com"], provenanceId, WorkBasis, "gitbook"),
        Critical("critical-postman", "Postman", ["postman.com"], provenanceId, CloudBasis, "postman"),
        Critical("critical-zapier", "Zapier", ["zapier.com"], provenanceId, WorkBasis, "zapier"),
        Critical("critical-docusign", "DocuSign", ["docusign.com"], provenanceId, WorkBasis, "docusign"),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateCommerceAndTravelRecords(
        string provenanceId) =>
    [
        Critical("critical-kaufland", "Kaufland", ["kaufland.de"], provenanceId, CommerceBasis, "kaufland"),
        Critical("critical-lidl", "Lidl", ["lidl.de"], provenanceId, CommerceBasis, "lidl"),
        Critical("critical-rewe", "REWE", ["rewe.de"], provenanceId, CommerceBasis, "rewe"),
        Critical("critical-dm", "dm", ["dm.de"], provenanceId, CommerceBasis, "dmdrogerie"),
        Critical("critical-rossmann", "ROSSMANN", ["rossmann.de"], provenanceId, CommerceBasis, "rossmann"),
        Critical("critical-hm", "H&M", ["hm.com"], provenanceId, CommerceBasis, "handm"),
        Critical("critical-adidas", "adidas", ["adidas.com"], provenanceId, CommerceBasis, "adidas"),
        Critical("critical-nike", "Nike", ["nike.com"], provenanceId, CommerceBasis, "nike"),
        Critical("critical-decathlon", "Decathlon", ["decathlon.com"], provenanceId, CommerceBasis, "decathlon"),
        Critical("critical-walmart", "Walmart", ["walmart.com"], provenanceId, CommerceBasis, "walmart"),
        Critical("critical-target", "Target", ["target.com"], provenanceId, CommerceBasis, "target"),
        Critical("critical-costco", "Costco", ["costco.com"], provenanceId, CommerceBasis, "costco"),
        Critical("critical-bestbuy", "Best Buy", ["bestbuy.com"], provenanceId, CommerceBasis, "bestbuy"),
        Critical("critical-wayfair", "Wayfair", ["wayfair.com"], provenanceId, CommerceBasis, "wayfair"),
        Critical("critical-rakuten", "Rakuten", ["rakuten.com"], provenanceId, CommerceBasis, "rakuten"),
        Critical("critical-mercadolibre", "Mercado Libre", ["mercadolibre.com"], provenanceId, CommerceBasis,
            "mercadolibre"),
        Critical("critical-shopee", "Shopee", ["shopee.com"], provenanceId, CommerceBasis, "shopee"),
        Critical("critical-coupang", "Coupang", ["coupang.com"], provenanceId, CommerceBasis, "coupang"),
        Critical("critical-avito", "Avito", ["avito.ru"], provenanceId, CommerceBasis, "avito"),
        Critical("critical-craigslist", "Craigslist", ["craigslist.org"], provenanceId, CommerceBasis, "craigslist"),
        Critical("critical-instacart", "Instacart", ["instacart.com"], provenanceId, CommerceBasis, "instacart"),
        Critical("critical-doordash", "DoorDash", ["doordash.com"], provenanceId, CommerceBasis, "doordash"),
        Critical("critical-deliveroo", "Deliveroo", ["deliveroo.com"], provenanceId, CommerceBasis, "deliveroo"),
        Critical("critical-wolt", "Wolt", ["wolt.com"], provenanceId, CommerceBasis, "wolt"),
        Critical("critical-hellofresh", "HelloFresh", ["hellofresh.com"], provenanceId, CommerceBasis, "hellofresh"),
        Critical("critical-expedia", "Expedia", ["expedia.com", "hotels.com"], provenanceId, TravelBasis,
            "expedia", "hotelscom"),
        Critical("critical-agoda", "Agoda", ["agoda.com"], provenanceId, TravelBasis, "agoda"),
        Critical("critical-skyscanner", "Skyscanner", ["skyscanner.net"], provenanceId, TravelBasis, "skyscanner"),
        Critical("critical-flixbus", "FlixBus", ["flixbus.com"], provenanceId, TravelBasis, "flixbus"),
        Critical("critical-deutsche-bahn", "Deutsche Bahn", ["bahn.de"], provenanceId, TravelBasis,
            "deutschebahn", "bahn"),
        Critical("critical-lufthansa", "Lufthansa", ["lufthansa.com"], provenanceId, TravelBasis, "lufthansa"),
        Critical("critical-ryanair", "Ryanair", ["ryanair.com"], provenanceId, TravelBasis, "ryanair"),
        Critical("critical-easyjet", "easyJet", ["easyjet.com"], provenanceId, TravelBasis, "easyjet"),
        Critical("critical-british-airways", "British Airways", ["britishairways.com"], provenanceId, TravelBasis,
            "britishairways"),
        Critical("critical-emirates", "Emirates", ["emirates.com"], provenanceId, TravelBasis, "emirates"),
        Critical("critical-delta", "Delta Air Lines", ["delta.com"], provenanceId, TravelBasis, "deltaairlines"),
        Critical("critical-united", "United Airlines", ["united.com"], provenanceId, TravelBasis, "unitedairlines"),
        Critical("critical-american-airlines", "American Airlines", ["aa.com"], provenanceId, TravelBasis,
            "americanairlines"),
        Critical("critical-southwest", "Southwest Airlines", ["southwest.com"], provenanceId, TravelBasis,
            "southwestairlines"),
        Critical("critical-flying-blue", "Air France / KLM Flying Blue", ["airfrance.com", "klm.com"],
            provenanceId, TravelBasis, "airfrance", "klm", "flyingblue"),
        Critical("critical-lyft", "Lyft", ["lyft.com"], provenanceId, TravelBasis, "lyft"),
        Critical("critical-bolt", "Bolt", ["bolt.eu"], provenanceId, TravelBasis, "bolt"),
        Critical("critical-freenow", "FREENOW", ["free-now.com"], provenanceId, TravelBasis, "freenow"),
        Critical("critical-sixt", "SIXT", ["sixt.com"], provenanceId, TravelBasis, "sixt"),
        Critical("critical-europcar", "Europcar", ["europcar.com"], provenanceId, TravelBasis, "europcar"),
        Critical("critical-hertz", "Hertz", ["hertz.com"], provenanceId, TravelBasis, "hertz"),
        Critical("critical-enterprise", "Enterprise", ["enterprise.com"], provenanceId, TravelBasis, "enterprise"),
        Critical("critical-marriott", "Marriott Bonvoy", ["marriott.com"], provenanceId, TravelBasis, "marriott"),
        Critical("critical-hilton", "Hilton Honors", ["hilton.com"], provenanceId, TravelBasis, "hilton"),
        Critical("critical-accor", "ALL / Accor", ["accor.com"], provenanceId, TravelBasis, "accor", "allaccor"),
        Critical("critical-ihg", "IHG One Rewards", ["ihg.com"], provenanceId, TravelBasis, "ihg"),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateCommunicationRecords(string provenanceId) =>
    [
        Critical("critical-twitch", "Twitch", ["twitch.tv"], provenanceId, CommunicationBasis, "twitch"),
        Critical("critical-tumblr", "Tumblr", ["tumblr.com"], provenanceId, CommunicationBasis, "tumblr"),
        Critical("critical-quora", "Quora", ["quora.com"], provenanceId, CommunicationBasis, "quora"),
        Critical("critical-stackexchange", "Stack Exchange", ["stackexchange.com"], provenanceId,
            CommunicationBasis, "stackexchange"),
        Critical("critical-patreon", "Patreon", ["patreon.com"], provenanceId, CommunicationBasis, "patreon"),
        Critical("critical-onlyfans", "OnlyFans", ["onlyfans.com"], provenanceId, CommunicationBasis, "onlyfans"),
        Critical("critical-meetup", "Meetup", ["meetup.com"], provenanceId, CommunicationBasis, "meetup"),
        Critical("critical-nextdoor", "Nextdoor", ["nextdoor.com"], provenanceId, CommunicationBasis, "nextdoor"),
        Critical("critical-vk", "VK", ["vk.com"], provenanceId, CommunicationBasis, "vk", "vkontakte"),
        Critical("critical-weibo", "Weibo", ["weibo.com"], provenanceId, CommunicationBasis, "weibo"),
        Critical("critical-line", "LINE", ["line.me"], provenanceId, CommunicationBasis, "line"),
        Critical("critical-kakao", "Kakao", ["kakao.com"], provenanceId, CommunicationBasis, "kakao"),
        Critical("critical-viber", "Viber", ["viber.com"], provenanceId, CommunicationBasis, "viber"),
        Critical("critical-substack", "Substack", ["substack.com"], provenanceId, CommunicationBasis, "substack"),
        Critical("critical-flickr", "Flickr", ["flickr.com"], provenanceId, CommunicationBasis, "flickr"),
        Critical("critical-clubhouse", "Clubhouse", ["clubhouse.com"], provenanceId, CommunicationBasis,
            "clubhouse"),
        Critical("critical-mastodon-social", "mastodon.social", ["mastodon.social"], provenanceId,
            CommunicationBasis, "mastodonsocial"),
        Critical("critical-truth-social", "Truth Social", ["truthsocial.com"], provenanceId,
            CommunicationBasis, "truthsocial"),
        Critical("critical-gab", "Gab", ["gab.com"], provenanceId, CommunicationBasis, "gab"),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateGamingRecords(string provenanceId) =>
    [
        Critical("critical-steam", "Steam", ["steampowered.com", "steamcommunity.com"], provenanceId,
            GamingBasis, "steam"),
        Critical("critical-playstation", "PlayStation", ["playstation.com"], provenanceId, GamingBasis,
            "playstation"),
        Critical("critical-nintendo", "Nintendo", ["nintendo.com"], provenanceId, GamingBasis, "nintendo"),
        Critical("critical-epic-games", "Epic Games", ["epicgames.com"], provenanceId, GamingBasis, "epicgames"),
        Critical("critical-gog", "GOG", ["gog.com"], provenanceId, GamingBasis, "gog"),
        Critical("critical-ea", "Electronic Arts", ["ea.com"], provenanceId, GamingBasis, "electronicarts", "ea"),
        Critical("critical-ubisoft", "Ubisoft", ["ubisoft.com"], provenanceId, GamingBasis, "ubisoft"),
        Critical("critical-battlenet", "Battle.net", ["battle.net"], provenanceId, GamingBasis, "battlenet", "blizzard"),
        Critical("critical-riot-games", "Riot Games", ["riotgames.com"], provenanceId, GamingBasis, "riotgames"),
        Critical("critical-roblox", "Roblox", ["roblox.com"], provenanceId, GamingBasis, "roblox"),
        Critical("critical-jagex", "Jagex", ["jagex.com"], provenanceId, GamingBasis, "jagex", "runescape"),
        Critical("critical-wargaming", "Wargaming", ["wargaming.net"], provenanceId, GamingBasis, "wargaming"),
        Critical("critical-gaijin", "Gaijin", ["gaijin.net"], provenanceId, GamingBasis, "gaijin"),
        Critical("critical-hoyoverse", "HoYoverse", ["hoyoverse.com"], provenanceId, GamingBasis, "hoyoverse"),
        Critical("critical-supercell", "Supercell", ["supercell.com"], provenanceId, GamingBasis, "supercell"),
        Critical("critical-bethesda", "Bethesda", ["bethesda.net"], provenanceId, GamingBasis, "bethesda"),
        Critical("critical-square-enix", "Square Enix", ["square-enix-games.com"], provenanceId, GamingBasis,
            "squareenix"),
        Critical("critical-nexon", "Nexon", ["nexon.com"], provenanceId, GamingBasis, "nexon"),
        Critical("critical-ncsoft", "NCSOFT", ["ncsoft.com"], provenanceId, GamingBasis, "ncsoft"),
        Critical("critical-pearl-abyss", "Pearl Abyss", ["pearlabyss.com"], provenanceId, GamingBasis,
            "pearlabyss"),
        Critical("critical-ccp-games", "CCP Games", ["ccpgames.com"], provenanceId, GamingBasis, "ccpgames"),
        Critical("critical-warframe", "Warframe", ["warframe.com"], provenanceId, GamingBasis, "warframe"),
        Critical("critical-bungie", "Bungie", ["bungie.net"], provenanceId, GamingBasis, "bungie"),
        Critical("critical-humble-bundle", "Humble Bundle", ["humblebundle.com"], provenanceId, GamingBasis,
            "humblebundle"),
        Critical("critical-fanatical", "Fanatical", ["fanatical.com"], provenanceId, GamingBasis, "fanatical"),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateGovernmentHealthAndInsuranceRecords(
        string provenanceId) =>
    [
        Critical("critical-login-gov", "Login.gov", ["login.gov"], provenanceId, GovernmentBasis, "logingov"),
        Critical("critical-mygov-au", "myGov Australia", ["my.gov.au"], provenanceId, GovernmentBasis, "mygovau"),
        Critical("critical-digid", "DigiD", ["digid.nl"], provenanceId, GovernmentBasis, "digid"),
        Critical("critical-mitid", "MitID", ["mitid.dk"], provenanceId, GovernmentBasis, "mitid"),
        Critical("critical-bankid", "BankID", ["bankid.com"], provenanceId, GovernmentBasis, "bankid"),
        Critical("critical-idporten", "ID-porten", ["idporten.no"], provenanceId, GovernmentBasis, "idporten"),
        Critical("critical-suomifi", "Suomi.fi e-Identification", ["suomi.fi"], provenanceId, GovernmentBasis,
            "suomifi"),
        Critical("critical-eestiee", "Eesti.ee", ["eesti.ee"], provenanceId, GovernmentBasis, "eestiee"),
        Critical("critical-clave", "Cl@ve", ["clave.gob.es"], provenanceId, GovernmentBasis, "clave"),
        Critical("critical-cie-it", "CIE Italy", ["cie.gov.it"], provenanceId, GovernmentBasis, "cieid"),
        Critical("critical-irs", "IRS Online Account", ["irs.gov"], provenanceId, GovernmentBasis, "irsaccount"),
        Critical("critical-ssa", "Social Security Administration", ["ssa.gov"], provenanceId, GovernmentBasis,
            "socialsecurityaccount"),
        Critical("critical-dak", "DAK-Gesundheit", ["dak.de"], provenanceId, HealthBasis, "dak"),
        Critical("critical-ikk-classic", "IKK classic", ["ikk-classic.de"], provenanceId, HealthBasis, "ikkclassic"),
        Critical("critical-hkk", "hkk Krankenkasse", ["hkk.de"], provenanceId, HealthBasis, "hkk"),
        Critical("critical-hek", "HEK", ["hek.de"], provenanceId, HealthBasis, "hek"),
        Critical("critical-kkh", "KKH", ["kkh.de"], provenanceId, HealthBasis, "kkh"),
        Critical("critical-debeka", "Debeka", ["debeka.de"], provenanceId, InsuranceBasis, "debeka"),
        Critical("critical-signal-iduna", "SIGNAL IDUNA", ["signal-iduna.de"], provenanceId, InsuranceBasis,
            "signaliduna"),
        Critical("critical-ruv", "R+V Versicherung", ["ruv.de"], provenanceId, InsuranceBasis, "ruv"),
        Critical("critical-generali-de", "Generali Germany", ["generali.de"], provenanceId, InsuranceBasis,
            "generalide"),
        Critical("critical-ergo", "ERGO", ["ergo.de"], provenanceId, InsuranceBasis, "ergo"),
        Critical("critical-zurich-de", "Zurich Germany", ["zurich.de"], provenanceId, InsuranceBasis,
            "zurichde"),
        Critical("critical-gothaer", "Gothaer", ["gothaer.de"], provenanceId, InsuranceBasis, "gothaer"),
        Critical("critical-jameda", "jameda", ["jameda.de"], provenanceId, HealthBasis, "jameda"),
        Critical("critical-zocdoc", "Zocdoc", ["zocdoc.com"], provenanceId, HealthBasis, "zocdoc"),
        Critical("critical-mychart", "MyChart", ["mychart.com"], provenanceId, HealthBasis, "mychart"),
        Critical("critical-geico", "GEICO", ["geico.com"], provenanceId, InsuranceBasis, "geico"),
        Critical("critical-progressive", "Progressive", ["progressive.com"], provenanceId, InsuranceBasis,
            "progressive"),
        Critical("critical-state-farm", "State Farm", ["statefarm.com"], provenanceId, InsuranceBasis,
            "statefarm"),
        Critical("critical-aviva", "Aviva", ["aviva.com"], provenanceId, InsuranceBasis, "aviva"),
        Critical("critical-aig", "AIG", ["aig.com"], provenanceId, InsuranceBasis, "aig"),
        Critical("critical-cigna", "Cigna", ["cigna.com"], provenanceId, InsuranceBasis, "cigna"),
        Critical("critical-united-healthcare", "UnitedHealthcare", ["uhc.com"], provenanceId, InsuranceBasis,
            "unitedhealthcare"),
        Critical("critical-bupa", "Bupa", ["bupa.com"], provenanceId, InsuranceBasis, "bupa"),
    ];

    private static IReadOnlyList<AccountClassificationProviderRecord> CreateLowerImpactRecords(string provenanceId) =>
    [
        NonCritical("noncritical-crunchyroll", "Crunchyroll", ["crunchyroll.com"], provenanceId, "crunchyroll"),
        NonCritical("noncritical-mubi", "MUBI", ["mubi.com"], provenanceId, "mubi"),
        NonCritical("noncritical-vimeo", "Vimeo", ["vimeo.com"], provenanceId, "vimeo"),
        NonCritical("noncritical-paramountplus", "Paramount+", ["paramountplus.com"], provenanceId,
            "paramountplus"),
        NonCritical("noncritical-peacock", "Peacock", ["peacocktv.com"], provenanceId, "peacock"),
        NonCritical("noncritical-discoveryplus", "discovery+", ["discoveryplus.com"], provenanceId,
            "discoveryplus"),
        NonCritical("noncritical-rtlplus", "RTL+", ["rtlplus.com"], provenanceId, "rtlplus"),
        NonCritical("noncritical-joyn", "Joyn", ["joyn.de"], provenanceId, "joyn"),
        NonCritical("noncritical-tunein", "TuneIn", ["tunein.com"], provenanceId, "tunein"),
        NonCritical("noncritical-tidal", "TIDAL", ["tidal.com"], provenanceId, "tidal"),
        NonCritical("noncritical-reuters", "Reuters", ["reuters.com"], provenanceId, "reuters"),
        NonCritical("noncritical-cnn", "CNN", ["cnn.com"], provenanceId, "cnn"),
        NonCritical("noncritical-washington-post", "The Washington Post", ["washingtonpost.com"], provenanceId,
            "washingtonpost"),
        NonCritical("noncritical-wsj", "The Wall Street Journal", ["wsj.com"], provenanceId, "wsj"),
        NonCritical("noncritical-bloomberg", "Bloomberg", ["bloomberg.com"], provenanceId, "bloomberg"),
        NonCritical("noncritical-ft", "Financial Times", ["ft.com"], provenanceId, "financialtimes"),
        NonCritical("noncritical-economist", "The Economist", ["economist.com"], provenanceId, "economist"),
        NonCritical("noncritical-lemonde", "Le Monde", ["lemonde.fr"], provenanceId, "lemonde"),
        NonCritical("noncritical-lefigaro", "Le Figaro", ["lefigaro.fr"], provenanceId, "lefigaro"),
        NonCritical("noncritical-elpais", "El País", ["elpais.com"], provenanceId, "elpais"),
        NonCritical("noncritical-corriere", "Corriere della Sera", ["corriere.it"], provenanceId, "corriere"),
        NonCritical("noncritical-repubblica", "la Repubblica", ["repubblica.it"], provenanceId, "repubblica"),
        NonCritical("noncritical-nzz", "Neue Zürcher Zeitung", ["nzz.ch"], provenanceId, "nzz"),
        NonCritical("noncritical-tagesanzeiger", "Tages-Anzeiger", ["tagesanzeiger.ch"], provenanceId,
            "tagesanzeiger"),
        NonCritical("noncritical-orf", "ORF", ["orf.at"], provenanceId, "orf"),
        NonCritical("noncritical-ard", "ARD", ["ard.de"], provenanceId, "ard"),
        NonCritical("noncritical-zdf", "ZDF", ["zdf.de"], provenanceId, "zdf"),
        NonCritical("noncritical-komoot", "Komoot", ["komoot.com"], provenanceId, "komoot"),
        NonCritical("noncritical-alltrails", "AllTrails", ["alltrails.com"], provenanceId, "alltrails"),
        NonCritical("noncritical-runkeeper", "Runkeeper", ["runkeeper.com"], provenanceId, "runkeeper"),
        NonCritical("noncritical-myfitnesspal", "MyFitnessPal", ["myfitnesspal.com"], provenanceId,
            "myfitnesspal"),
        NonCritical("noncritical-chesscom", "Chess.com", ["chess.com"], provenanceId, "chesscom"),
        NonCritical("noncritical-lichess", "Lichess", ["lichess.org"], provenanceId, "lichess"),
        NonCritical("noncritical-boardgamegeek", "BoardGameGeek", ["boardgamegeek.com"], provenanceId,
            "boardgamegeek"),
        NonCritical("noncritical-yelp", "Yelp", ["yelp.com"], provenanceId, "yelp"),
    ];

    private const string SecurityBasis =
        "Repository-reviewed security account that can control authentication, protected devices, or security services.";
    private const string IdentityBasis =
        "Repository-reviewed identity account that can grant access to connected services or synchronized identity data.";
    private const string CloudBasis =
        "Repository-reviewed cloud or developer account that can control code, packages, domains, infrastructure, or hosted data.";
    private const string WorkBasis =
        "Repository-reviewed work account that can expose organizational content, signatures, automation, or collaboration authority.";
    private const string CommerceBasis =
        "Repository-reviewed commerce account with saved payment, address, order, loyalty, or seller authority.";
    private const string TravelBasis =
        "Repository-reviewed travel account with bookings, payment, identity, location, or loyalty value.";
    private const string CommunicationBasis =
        "Repository-reviewed communications or social-identity account where takeover enables impersonation, publishing, or message access.";
    private const string GamingBasis =
        "Repository-reviewed gaming account with purchases, balance, tradable or valuable digital inventory, marketplace access, or material social identity.";
    private const string GovernmentBasis =
        "Repository-reviewed government or national identity account containing official identity, tax, benefit, or public-service access.";
    private const string HealthBasis =
        "Repository-reviewed health account containing medical, appointment, prescription, or coverage data.";
    private const string InsuranceBasis =
        "Repository-reviewed insurance account containing identity, policy, claim, payment, or coverage authority.";

    private static AccountClassificationProviderRecord Email(
        string id, string name, string[] domains, string provenanceId, params string[] aliases) =>
        Record(id, name, AccountRecoveryCategory.Email, domains, aliases, provenanceId,
            "Repository-reviewed provider-owned consumer mailbox family; mailbox access can reset other accounts.");

    private static AccountClassificationProviderRecord Financial(
        string id, string name, string[] domains, string provenanceId, params string[] aliases) =>
        Record(id, name, AccountRecoveryCategory.Critical, domains, aliases, provenanceId,
            "Repository-reviewed banking, payment, investment, or crypto account; takeover can affect money and identity.");

    private static AccountClassificationProviderRecord Critical(
        string id,
        string name,
        string[] domains,
        string provenanceId,
        string reviewBasis,
        params string[] aliases) =>
        Record(id, name, AccountRecoveryCategory.Critical, domains, aliases, provenanceId, reviewBasis);

    private static AccountClassificationProviderRecord NonCritical(
        string id, string name, string[] domains, string provenanceId, params string[] aliases) =>
        Record(id, name, AccountRecoveryCategory.NonCritical, domains, aliases, provenanceId,
            "Repository-reviewed consumer media, reading, fitness, or leisure account where delayed recovery is normally defensible and no trading or material asset authority was identified.");

    private static AccountClassificationProviderRecord Record(
        string id,
        string name,
        AccountRecoveryCategory category,
        string[] domains,
        string[] aliases,
        string provenanceId,
        string reviewBasis) =>
        new(
            id,
            name,
            category,
            Array.AsReadOnly(domains),
            Array.AsReadOnly(aliases),
            provenanceId,
            reviewBasis);
}
